pioneers/runtime

- dev_handler/devices.c
- dev_handler/devices.h
- dev_handler/message.c
- runtime_util/runtime_util.h
Will still need work on message.c/.h but devices.c/devices.h should be functional.
> Fixes to devices.c, devices.h, and runtime_utils with successful compiling.

- logger/logger.c
- logger/logger_config.h
- shm_wrapper/shm_wrapper.c
- shm_wrapper/shm_wrapper_test1.c
- shm_wrapper/shm_wrapper_test2.c
1) switched DEBUG and INFO log levels
2) bug fix to shm wrapper test
> [SHM_WRAPPER][LOGGER] minor fixes

- zmq_comm/client.c
- zmq_comm/server.c
- zmq_comm/types.h
Moving changes in `zmq_comm` to `net_handler`
> basic zmq test

- .gitattributes
- executor/studentapi.pxd
- executor/studentapi.pyx
- logger/logger.c
- logger/logger.h
- shm_wrapper/shm_wrapper.c
- shm_wrapper_aux/shm_wrapper_aux.c
Removed `log_runtime` from project and converted to `log_printf`. `log_runtime` is not in `logger` any more either.
> [LOGGER] Remove all log_runtime in project

- .dockerignore
- .gitignore
- .travis.yml
- Dockerfile
- build.sh
- create_static_shm.sh
- executor/Makefile
- net_handler/net_handler.c
- net_handler/test/tcp_client.c
- run.sh
We now have a working docker image from https://hub.docker.com/repository/docker/avsurfer123/c-runtime. The Travis CI uses this image to check if the code is working. The test currently run is just running `tcp_client` and `udp_client` once. But eventually we will replace this with the new `net_handler` tests.
> [BUILD] Working Docker image and using it for Travis CI

- .travis.yml
- docker/README.md
- net_handler/Makefile
- Having Travis rebuild the docker image each time from the image cache it pulled
- Adding deploy stage to automatically update Docker image on DockerHub on push to `master`
> [BUILD] Made Travis build image from cache. Added deploy push

- executor/executor.c
- executor/studentapi.pyx
- executor/studentcode.py
Closes #54 by adding GIL ensure and release in the `python_exit_handler`. Also ended up creating a custom `Robot.sleep` function to replace the `time.sleep` so that the main thread is correctly cancelled when the mode changes.
> [EXECUTOR] Added Robot.sleep and GIL lock to fix time.sleep bug

- dev_handler/Makefile
- dev_handler/README.md
- dev_handler/dev_handler.c
- dev_handler/message.h
- lowcar/devices/Device/Messenger.cpp
- lowcar/devices/Device/defs.h
- runtime_util/runtime_util.c
- runtime_util/runtime_util.h
- tests/integration/tc_68_14.c
- Reduced sleep in dev_handler poll_connected_devices and relayer
- Removed devices we are not currently supporting in runtime_util.h
- Fixed spacing issue
> [MISC] Dev handler and util clean up

- test.sh
- tests/test.c
- tests/test.h
As per title of pull request. Removes the need of a temp file in test framework.
> [TEST] Changed test.c to use thread, not process. Remove temp file

- net_handler/udp_conn.c
- tests/integration/tc_71_17.c
- tests/integration/tc_71_18.c
- tests/integration/tc_71_4.c
While working on Dawn, I found that the current Gamepad connection check is flawed and so I fixed it.
Also, having a nonzero uid for the CustomData is easier since the uid 0 is the default Protobuf value corresponding to 0 bytes and makes life really annoying in Dawn.
> [MISC] Gamepad error check

- dev_handler/dev_handler.c
- dev_handler/message.c
- executor/executor.c
- net_handler/net_util.c
- net_handler/tcp_conn.c
- net_handler/udp_conn.c
- tests/cli/net_handler_cli.c
- tests/client/dev_handler_client.c
- tests/client/executor_client.c
- tests/client/net_handler_client.c
- tests/client/virtual_devices/virtual_device_util.c
- tests/test.c
- If null, write a FATAL log and exit(1)
- Didn't add checks for Arduino files and protobuf_test files
Closes #121
> [MISC] Add null checks for malloc

- net_handler/net_handler.c
- net_handler/net_util.c
- net_handler/net_util.h
- net_handler/tcp_conn.c
- tests/client/net_handler_client.c
- Added descriptions for `#define`s in `net_util.h`
- Renamed `RASPI_PORT` to `RASPI_TCP_PORT`
- Fixed indexing bug for unpacking subscriptions
- Extended malloc error fatal log message for debugging
> [NET_HANDLER] Add comments and fix indexing bug

- shm_wrapper/shm_start.c
- shm_wrapper/shm_wrapper.c
- shm_wrapper/shm_wrapper.h
- tests/cli/net_handler_cli.c
- Net Handler CLI
- Properly malloc and populate device names for subs
- Prompt "done?" only after at least one subscription
- Make pressing enter as a response to default actions
- Shared Memory
- Add/clarify comments in shm_start and shm_wrapper
> [TEST] Fix net_handler_cli bug with device data

- runtime
Small additions to the runtime script to display a brief description and common usage for each command.
Closes #163
> [MISC] Display help for runtime script

- scripts/test.sh
- A test fails only if exit code is nonzero
Resolves #174
> [TEST] Fix failing test condition

- tests/README.md
- tests/cli/shm_ui.c
This implements half of issue #118 , the other half (attaching `net_handler_cli`) is WIP but this issue is so useful that we should get it merged in ASAP.
> [TEST] Adds attach mode to shm_ui

- systemd/ngrok.yml
> Added ssh port to ngrok

- net_handler/tcp_conn.c
- tests/integration/tc_150_1.c
- tests/integration/tc_159_1.c
- tests/integration/tc_203_1.c
- tests/integration/tc_71_2.c
- Added a long if statement in `tcp_conn.c` to implement desired behavior
- Also disconnected keyboard on Dawn disconnection
Closes #203
> [NET_HANDLER] Implemented issue #203

- lowcar/devices/KoalaBear/KoalaBear.cpp
- lowcar/devices/PDB/PDB.h
Removed device_enable from PDB.h and set pid_enabled to false for KoalaBear.cpp.
> [LOWCAR] Small fixes to KoalaBear

- tests/client/dev_handler_client.c
- tests/client/dev_handler_client.h
- tests/client/executor_client.c
- tests/client/executor_client.h
- tests/client/net_handler_client.c
- tests/client/net_handler_client.h
- tests/client/shm_client.c
- tests/client/shm_client.h
RESOLVED #242 
Replaced all printf statements with log_printf statements for all cpp files in the test folder.
> [TEST] replaced all printf statements with log_printf

- tests/student_code/executor_sanity.py
- tests/student_code/keyboard_input.py
- tests/student_code/net_handler_integration.py
- tests/student_code/runtime_latency.py
- tests/student_code/sanity_write.py
> Revert "modified first 5 student_code tests"

- executor/studentcode.py
- tests/student_code/executor_sanity.py
- tests/student_code/keyboard_input.py
- tests/student_code/net_handler_integration.py
- tests/student_code/runtime_latency.py
- tests/student_code/sanity_write.py
Modified the first 5 python files in tests/student_code, and the studentcode.py file in executor; so as to match with the new executor.
> Modified studentcode files

- executor/executor.c
- executor/studentcode.py
- net_handler/net_handler_message.c
- tests/student_code/sound_device.py
- tests/student_code/tc_212_a.py
- tests/student_code/tc_212_b.py
- tests/student_code/tc_212_c.py
Changed lines 113 - 116 and 130 - 132 to account for the new custom device. Initialized num_devices and loop index 'i' as 1 instead of 0 to leave the first slot open.
> Updated net_handler_message.c to account for new custom device
