pioneers/runtime

runtime_util/runtime_util.h
shm_wrapper/Makefile
shm_wrapper/connect_static_devices.c
shm_wrapper/shm_wrapper.c
shm_wrapper/shm_wrapper.h
shm_wrapper/shm_wrapper_test1.c
shm_wrapper/shm_wrapper_test2.c
shm_wrapper_aux/Makefile
shm_wrapper_aux/shm_wrapper_aux.c
shm_wrapper_aux/shm_wrapper_aux.h
shm_wrapper_aux/shm_wrapper_aux_test1.c
shm_wrapper_aux/shm_wrapper_aux_test2.c

- Added shm_wrapper_aux and suite of tests, including printing utilities; added Makefile
- Bug fixes on the synchronization function used to execute the shm wrapper tests consistently
- Added read and write functions for the device shm wrapper that allow user to reference devices with their 64-bit unique ID number, instead of their device index
- Added a file that just spawns the maximum number of devices in their shared memory wrapper for the executor to read
- Inserted logger messages into both shared memory wrappers

[SHM_WRAPPER] added shm_wrapper_aux and associated tests; bug fixes on device shm wrapper

---

logger/logger.c
logger/logger_config.h
runtime_util/runtime_util.h
shm_wrapper/shm_wrapper.c
shm_wrapper_aux/shm_wrapper_aux.c
shm_wrapper_aux/shm_wrapper_aux.h
shm_wrapper_aux/shm_wrapper_aux_test1.c
shm_wrapper_aux/shm_wrapper_aux_test2.c

1) Added `STUDENTAPI` as a possible process
2) Cleaned up semaphore logic in both wrapper significantly (considering putting the `my_sem_*` functions in `runtime_util` actually, but for now they can stay in the wrappers)
3) Removed `process` argument from `gamepad_read` and `gamepad_write` functions

[SHM_WRAPPER] minor cleanups and additions to shm wrappers

---

.travis.yml
docker/README.md
net_handler/Makefile
net_handler/net_handler.c
net_handler/pbc_gen/device.pb-c.c
net_handler/pbc_gen/device.pb-c.h
net_handler/protos/device.proto
net_handler/tcp_conn.c
net_handler/test/tcp_client.c
net_handler/test/udp_client.c
net_handler/udp_conn.c
shm_wrapper/print_shm.c
shm_wrapper/shm.c
shm_wrapper/shm_wrapper.c
shm_wrapper/shm_wrapper.h
shm_wrapper/shm_wrapper_test1.c

Closes #40 
- Changed get_sub_requests to be different depending on the calling process
- Made net_handler subscriptions be default on, so that student can at first see all devices
- Added DevData processing code to tcp_conn which places sub requests
- Added check for the current sub requests when sending data in udp_conn
- Added test code in tcp_client to turn polarbear data off and on

[SHM][NET_HANDLER] Added subscription requests to net_handler

---

build.sh
docker/README.md
docker/base/Dockerfile
executor/executor.c
executor/runtime.pxd
executor/studentapi.pyx
executor/studentcode.py
net_handler/tcp_conn.c
net_handler/udp_conn.c
run.sh
runtime_util/runtime_util.c
runtime_util/runtime_util.h
shm_wrapper/print_shm.c
shm_wrapper/shm.c
shm_wrapper/shm_wrapper.c
shm_wrapper/shm_wrapper.h
test.sh
tests/client/net_handler_client.c
tests/integration/tc_68_4.c
tests/test.c

Closes #64 
In order to do this:
- a new SHM block was added called `log_data` and has a corresponding semaphore
- new SHM functions were added that can read, write, and print this data
- new API function Robot.log was added that calls `log_data_write`
- udp_conn's send_device_data was modified to add on a CustomData device with these logged parameters
- as a bonus, the CustomData will always include the number of milliseconds since the Robot started so making graphs is easier for Dawn

Adds a Robot.log function to log arbitrary data, not just device params

---

docker-compose.yml
docker/README.md
logger/logger.config
tests/cli/net_handler_cli.c

Fixing the docker-compose command, and making it so that by default, the container doesn't run Runtime. The developer now must run the `runtime` commands manually when they wish.

[DOCKER] Fixing docker-compose, and not running Runtime by default

---

docker/base/Dockerfile
tests/cli/net_handler_cli.c
tests/client/net_handler_client.c
tests/client/net_handler_client.h

Added `reroute output` command to `net_handler_cli` to redirect some outputs in the net handler CLI to a separate file to avoid overcrowding the net handler terminal window. 
Closes issue #79

[TEST] Added support for rerouting output in net_handler_cli

---

dev_handler/dev_handler.c

See linked issue for explanation of bug. This change fixes said bug!
- Added flag `O_NOCTTY` to line 711 of `dev_handler.c`
- Change prevents connecting devices from becoming controlling terminals
Closes #145

[DEV_HANDLER] Fixes runtime crash when running as systemd

---

scripts/run.sh
systemd/dev_handler.service
systemd/executor.service
systemd/net_handler.service
systemd/shm_stop.service

Much simpler change than anticipated! I think it was a combination of a typo in `shm_stop.service` and me adding more `Before` and `After` dependencies to the services.
- Changed type of net_handler, dev_handler, and executor services to "`simple`"
- Listed `shm_start.service` as an `OnFailure` dependency of `shm_stop` (I think this was a typo before)
- Was working on a different solution before and added some comments to `run.sh`
I tested this and it does seem to work, if you try killing one of the processes using `kill -6`, it instantaneously regenerates a new instance of Runtime. The change from `oneshot` to `simple` is more of an aesthetic thing; when the processes are running now and you do `systemctl status executor`, for example, it will display `active (running)` as its status in …

[SYSTEMD] Implementing circular restarting of Runtime

---

net_handler/tcp_conn.c

- Free all allocated memory before returning
- Call function iff FIFO does not have an EOF
Resolves #136 -- We were not properly `free()`ing memory before returning
Finding this bug made it clear that `tcp_conn.c` is still being spammed with `EOF`, even though not all write-ends are closed.
As a result, we re-opened #82

[NET_HANDLER] Fix memory leak in send_log_msg()

---

lowcar/devices/Device/Messenger.cpp
lowcar/devices/KoalaBear/KoalaBear.cpp
lowcar/devices/KoalaBear/KoalaBear.h
lowcar/devices/KoalaBear/PID.cpp
lowcar/devices/KoalaBear/PID.h

Provides for additional adjustability and fine-tuning of the performance of KoalaBears. Several features are added:
- An acceleration constant, which allows us to control how fast a robot can get up to speed (which also dictates how much "inertia" the robot has when slowing down)
- A more accurate calculation of the derivative term of the PID control loop, using a linear regression of a few of the most recent samples of the motor state
- A more thorough attempt at tuning the PID controller coefficients that were determined empirically without tools on staff curry and with the motors free-spinning (in an attempt to make the coefficients usable in many situations)
This also includes a few bug fixes in lowcar:
- Fixed "jumping" when first plugging in the KoalaBear by adding in the variable …

[LOWCAR] Working and tuned KoalaBear PID control and acceleration

---

dev_handler/dev_handler.c
runtime_util/runtime_util.h
tests/cli/dev_handler_cli.c
tests/cli/net_handler_cli.c
tests/client/dev_handler_client.c
tests/client/dev_handler_client.h
tests/client/net_handler_client.c
tests/client/net_handler_client.h

Net handler CLI and dev handler CLI can now "attach" to their respective existing instances of runtime instead of spawning a new instance.
- Net handler CLI can specify zero or more flags from (`-d` and `-s`)
- Without arguments it spawns a new net handler instance and connects a fake Dawn and fake Shepherd.
- This is unchanged and the same behavior as on `master`.
- `-d` : Does not spawn a new net handler; Connects a fake Dawn
- `-s` : Does not spawn a new net handler; Connects a fake Shepherd
- Dev handler no longer takes in arguments.
- Dev handler now detects BOTH Arduinos and virtual devices.
- Dev handler CLI has an optional argument `attach`.
- Without this argument, it spawns a new dev handler. This is unchanged and the same behavior as on `master`.
- With this argument, it …

[NET_HANDLER][DEV_HANDLER][CLI] Add CLI attaching

---

systemd/ngrok.sh
systemd/ngrok_displayer.py
systemd/ngrok_displayer.service

- `ngrok_displayer` is its own service.
- Accessing `/new` endpoint will restart `ngrok.service` first.
- Refreshing webpage will fetch the current IP addresses before
displaying anything.
Resolves #197

[MISC] Implement ngrok restarting from webpage

---

shm_wrapper/shm_wrapper.c
shm_wrapper/shm_wrapper.h
tests/cli/shm_ui.c

- UI fails in attach mode if shm doesn't exist.
- UI polls for the existence of shm and will exit if it was destroyed.
- Fix minor visual bug with the note at the bottom of the UI not displaying properly.

[SHM][UI] Add check in shm_init() that shm exists

---

executor/executor.c
net_handler/net_handler.c
net_handler/tcp_conn.c
net_handler/udp_conn.c

- signal handler for executor commented out
- log level dependent on signal received
- new protocol implemented for net_handler:
- Essentially determine the client, with a timeout if client ID isn't sent during a set amount of time
- Kill the previous version of dawn or shepherd and form a new connection with what is likely a new instance of Dawn and Shepherd

[EXECUTOR][NET_HANDLER] Changed log level in kill_subprocess()

---

dev_handler/dev_handler.c
dev_handler/message.c
dev_handler/message.h
lowcar/devices/Device/Device.cpp
lowcar/devices/Device/Device.h
lowcar/devices/Device/StatusLED.h
lowcar/devices/Device/defs.h
scripts/flash.sh
tests/client/virtual_devices/virtual_device_util.c

- The Device Type is a 1 byte value. This is already the case in the Runtime code, but it seems like we forgot to change this in the lowcar code.
- "Enabled" in lowcar is clarified to mean "connected to Runtime". In the constructor, `enabled` is false. When `enabled` is set to true (i.e. when the device sends an `ACK`), we call `device_enable()`.

[LOWCAR] Several lowcar fixes

---

executor/executor.c

- Had to put the student API import before the student code import so that the `stderr` gets redirected first so that import errors get correctly sent to the log FIFO

[EXECUTOR] Fix executor not printing import error message to net handler

---

scripts/flash.sh

Small QOL feature. This is especially useful for Shepherd, when they might have many Arduinos attached to the field control computer at the same time and specifically want to flash one of them. Could be useful for Runtime as well, if we're testing multiple devices on the Raspi and are flashing from it.
Also updated usage text with the new path flag (`-p`), and added list of available ports on computer as part of the help text.
Closes #202

[LOWCAR] Added optional path argument to flash script; resolves #202

---

docker/Dockerfile
systemd/set_time.service
systemd/set_time.sh

`set_time.service` and `set_time.sh` together will set the time on Raspberry Pi's because if they're connected to CalVisitor or Motherbase connected to CalVisitor, the raspberry pi's will not be able to access the NTP servers to get the current system clock, causing confusing Github messages and the like (certificate expired, certificate inactivated, etc.).
Travis used to not build the cli, which caused us to miss the dual `get_next_dev_data()` in `net_handler_cli` for months. Travis now builds the `cli` to make sure the they build properly in order to merge.
Closes #220

[SYSTEMD][BUILD] New set_time.service and Travis builds cli

---

dev_handler/Makefile
dev_handler/message.h
lowcar/devices/Device/Device.cpp
lowcar/devices/Device/Device.h
lowcar/devices/KoalaBear/KoalaBear.cpp

- Function call adds a sleep(1) that causes timeout issue
- Timeout reduced back to 1000ms, which was increased to 2000s as a short term solution
Issue #236 was originally thought to be the reason behind the timeout issue. This PR won't close that issue because the issue addresses the hacky solution of forcing a lowcar device to reset by pretending that dev handler dies.

[LOWCAR][DEV_HANDLER] Remove LED test in KoalaBear

---

tests/cli/shm_ui.c

Removes need to specify "attach" arg
```
if shm exists when shm_ui is started
shm_init()
else:
create shm
sleep(1)
And destroy shm on exit
```
This is part of issue #239. Completing this for shm_ui early because it can save us some headaches from forgetting to specify "attach".

[CLI] Auto attach SHM_UI iff shm exists on start

---

lowcar/devices/ServoControl/ServoControl.cpp

Divide by 2.0 is unnecessary and already accounted for in SERVO_RANGE

[LOWCAR] Fix Servo range of motion

---

lowcar/devices/LimitSwitch/LimitSwitch.cpp
lowcar/devices/LineFollower/LineFollower.cpp
lowcar/devices/ServoControl/ServoControl.cpp

RESOLVED #253 
We should make sure that device_read()/device_write() for all the devices return 0 if the param argument is invalid.
In LimitSwitch::device_read(), we call digitalRead() with the argument param, even if might not refer to a relevant pin.

[LOWCAR] make sure lowcar parameter is valid

---

lowcar/devices/Device/Device.cpp

RESOLVED #246
Added a line under Device Write case to update time every time we receive a device write ping.

[LOWCAR] updated time for recieving device writes as well

---

.github/workflows/pull_request_ci.yml

The idea behind putting a schedule on the CI build was to make sure that the cache never expired. However, since it seems that a cache is only valid when run on the same PR/same branch, this doesn’t matter since we won’t be able to transfer the cache between PRs or between a working branch and master. I removed it in this PR.

[BUILD] Removed cron trigger for workflow

---

lowcar/devices/Device/Device.cpp
lowcar/devices/ServoControl/ServoControl.cpp

broke in pull request #258, #256, #255

[LOWCAR] fixes compilation error for lowcar

---

.github/workflows/pull_request_ci.yml
systemd/ngrok.service
systemd/ngrok.sh
systemd/ngrok_displayer.service
systemd/set_time.service

Updated some systemd files that still had pi in the path and username instead of ubuntu. It's probably not completely necessary, but it is good that it is fully updated. I am also using this as an example of a pull request to show new members.

[SYSTEMD] updated last few files from pi to ubuntu

---

tests/student_code/sound_device.py
tests/student_code/tc_212_a.py
tests/student_code/tc_212_b.py
tests/student_code/tc_212_c.py

Updated last 4 files in tests/student_code to account for the updated executor. Replaced autonomous setup/main with autonomous() and teleop setup/main with teleop(), and added while True loops to simulate continuous execution.

Updated last 4 student code test files 
